/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface UserContractInterface extends ethers.utils.Interface {
  functions: {
    "callback(bytes32,string)": FunctionFragment;
    "queryResponses(bytes32)": FunctionFragment;
    "someFunc(string,string,string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "callback",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "queryResponses",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "someFunc",
    values: [string, string, string]
  ): string;

  decodeFunctionResult(functionFragment: "callback", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "queryResponses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "someFunc", data: BytesLike): Result;

  events: {
    "Query(bytes32)": EventFragment;
    "Response(bytes32,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Query"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Response"): EventFragment;
}

export type QueryEvent = TypedEvent<[string] & { queryId: string }>;

export type ResponseEvent = TypedEvent<
  [string, string] & { queryId: string; response: string }
>;

export class UserContract extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: UserContractInterface;

  functions: {
    callback(
      queryId: BytesLike,
      responseStr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    queryResponses(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean, string] & { exists: boolean; responseStr: string }>;

    someFunc(
      packageUri: string,
      method: string,
      argStr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  callback(
    queryId: BytesLike,
    responseStr: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  queryResponses(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<[boolean, string] & { exists: boolean; responseStr: string }>;

  someFunc(
    packageUri: string,
    method: string,
    argStr: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    callback(
      queryId: BytesLike,
      responseStr: string,
      overrides?: CallOverrides
    ): Promise<void>;

    queryResponses(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean, string] & { exists: boolean; responseStr: string }>;

    someFunc(
      packageUri: string,
      method: string,
      argStr: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Query(bytes32)"(
      queryId?: null
    ): TypedEventFilter<[string], { queryId: string }>;

    Query(queryId?: null): TypedEventFilter<[string], { queryId: string }>;

    "Response(bytes32,string)"(
      queryId?: null,
      response?: null
    ): TypedEventFilter<
      [string, string],
      { queryId: string; response: string }
    >;

    Response(
      queryId?: null,
      response?: null
    ): TypedEventFilter<
      [string, string],
      { queryId: string; response: string }
    >;
  };

  estimateGas: {
    callback(
      queryId: BytesLike,
      responseStr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    queryResponses(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    someFunc(
      packageUri: string,
      method: string,
      argStr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    callback(
      queryId: BytesLike,
      responseStr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    queryResponses(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    someFunc(
      packageUri: string,
      method: string,
      argStr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
